# Generated by Django 6.0.5 on 2026-05-31 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('counselors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisflag',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_flags', to='counselors.counselor'),
        ),
    ]
