# Generated by Django 6.0.5 on 2026-05-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Resource Categories'},
        ),
    ]
